### ISSUE TITLE
Problem with diagonal crossing

### ISSUE THREAD

**Issue by Daniel-Gill** [Railway-Op-Sim/UK-ClaphamJunction#3]
![image](https://user-images.githubusercontent.com/56364196/101169914-8d7edc00-3635-11eb-8372-f47aedb5b2c2.png)

Some routes cannot be made over this style of crossing.

**Comment by AlbertBall** [comment]
Is this a bug in the program (hopefully not!) or in the map?

**Comment by Daniel-Gill** [comment]
@AlbertBall I'm pretty sure this is a bug with the map caused by a very reasonable choice in the program!

**Comment by AlbertBall** [comment]
That's a relief!

**Comment by Daniel-Gill** [comment]
Fixed with 03ca308 and #4
